// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/agent/agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED  CommandType = 0
	CommandType_COMMAND_TYPE_EXEC         CommandType = 1 // Execute shell command
	CommandType_COMMAND_TYPE_INSTALL      CommandType = 2 // apt/yum install
	CommandType_COMMAND_TYPE_SERVICE      CommandType = 3 // systemctl start/stop/restart
	CommandType_COMMAND_TYPE_DOCKER       CommandType = 4 // Docker operations
	CommandType_COMMAND_TYPE_FILE         CommandType = 5 // File operations (read/write/delete)
	CommandType_COMMAND_TYPE_SCRIPT       CommandType = 6 // Execute script content
	CommandType_COMMAND_TYPE_SSH          CommandType = 7 // SSH key/config operations
	CommandType_COMMAND_TYPE_CHECK_MODULE CommandType = 8 // Check if module binaries exist on filesystem
	CommandType_COMMAND_TYPE_RECONNECT    CommandType = 9 // Internal blue-green deploy handoff signal
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0: "COMMAND_TYPE_UNSPECIFIED",
		1: "COMMAND_TYPE_EXEC",
		2: "COMMAND_TYPE_INSTALL",
		3: "COMMAND_TYPE_SERVICE",
		4: "COMMAND_TYPE_DOCKER",
		5: "COMMAND_TYPE_FILE",
		6: "COMMAND_TYPE_SCRIPT",
		7: "COMMAND_TYPE_SSH",
		8: "COMMAND_TYPE_CHECK_MODULE",
		9: "COMMAND_TYPE_RECONNECT",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":  0,
		"COMMAND_TYPE_EXEC":         1,
		"COMMAND_TYPE_INSTALL":      2,
		"COMMAND_TYPE_SERVICE":      3,
		"COMMAND_TYPE_DOCKER":       4,
		"COMMAND_TYPE_FILE":         5,
		"COMMAND_TYPE_SCRIPT":       6,
		"COMMAND_TYPE_SSH":          7,
		"COMMAND_TYPE_CHECK_MODULE": 8,
		"COMMAND_TYPE_RECONNECT":    9,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_agent_proto_enumTypes[0].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_proto_agent_agent_proto_enumTypes[0]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{0}
}

type CommandStatus int32

const (
	CommandStatus_COMMAND_STATUS_UNSPECIFIED CommandStatus = 0
	CommandStatus_COMMAND_STATUS_PENDING     CommandStatus = 1
	CommandStatus_COMMAND_STATUS_RUNNING     CommandStatus = 2
	CommandStatus_COMMAND_STATUS_COMPLETED   CommandStatus = 3
	CommandStatus_COMMAND_STATUS_FAILED      CommandStatus = 4
	CommandStatus_COMMAND_STATUS_TIMEOUT     CommandStatus = 5
	CommandStatus_COMMAND_STATUS_CANCELLED   CommandStatus = 6
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "COMMAND_STATUS_UNSPECIFIED",
		1: "COMMAND_STATUS_PENDING",
		2: "COMMAND_STATUS_RUNNING",
		3: "COMMAND_STATUS_COMPLETED",
		4: "COMMAND_STATUS_FAILED",
		5: "COMMAND_STATUS_TIMEOUT",
		6: "COMMAND_STATUS_CANCELLED",
	}
	CommandStatus_value = map[string]int32{
		"COMMAND_STATUS_UNSPECIFIED": 0,
		"COMMAND_STATUS_PENDING":     1,
		"COMMAND_STATUS_RUNNING":     2,
		"COMMAND_STATUS_COMPLETED":   3,
		"COMMAND_STATUS_FAILED":      4,
		"COMMAND_STATUS_TIMEOUT":     5,
		"COMMAND_STATUS_CANCELLED":   6,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_agent_proto_enumTypes[1].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_proto_agent_agent_proto_enumTypes[1]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{1}
}

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_LOG_LEVEL_DEBUG       LogLevel = 1
	LogLevel_LOG_LEVEL_INFO        LogLevel = 2
	LogLevel_LOG_LEVEL_WARN        LogLevel = 3
	LogLevel_LOG_LEVEL_ERROR       LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "LOG_LEVEL_DEBUG",
		2: "LOG_LEVEL_INFO",
		3: "LOG_LEVEL_WARN",
		4: "LOG_LEVEL_ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"LOG_LEVEL_DEBUG":       1,
		"LOG_LEVEL_INFO":        2,
		"LOG_LEVEL_WARN":        3,
		"LOG_LEVEL_ERROR":       4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_agent_proto_enumTypes[2].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_proto_agent_agent_proto_enumTypes[2]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{2}
}

type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	AgentStatus_AGENT_STATUS_IDLE        AgentStatus = 1
	AgentStatus_AGENT_STATUS_BUSY        AgentStatus = 2
	AgentStatus_AGENT_STATUS_ERROR       AgentStatus = 3
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "AGENT_STATUS_IDLE",
		2: "AGENT_STATUS_BUSY",
		3: "AGENT_STATUS_ERROR",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED": 0,
		"AGENT_STATUS_IDLE":        1,
		"AGENT_STATUS_BUSY":        2,
		"AGENT_STATUS_ERROR":       3,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_agent_proto_enumTypes[3].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_proto_agent_agent_proto_enumTypes[3]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{3}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`                                                          // Unique agent identifier (generated or assigned)
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`                                                                       // VPS hostname
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`                                                    // Public IP
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`                                                                                   // e.g., "ubuntu", "debian", "centos"
	OsVersion     string                 `protobuf:"bytes,5,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`                                                    // e.g., "22.04"
	Arch          string                 `protobuf:"bytes,6,opt,name=arch,proto3" json:"arch,omitempty"`                                                                               // e.g., "amd64", "arm64"
	AgentVersion  string                 `protobuf:"bytes,7,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`                                           // Agent binary version
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Custom labels for grouping
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type RegisterResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message           string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AssignedId        string                 `protobuf:"bytes,3,opt,name=assigned_id,json=assignedId,proto3" json:"assigned_id,omitempty"`                       // Control Plane may assign a different ID
	HeartbeatInterval int32                  `protobuf:"varint,4,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"` // Seconds between heartbeats
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponse) GetAssignedId() string {
	if x != nil {
		return x.AssignedId
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatInterval() int32 {
	if x != nil {
		return x.HeartbeatInterval
	}
	return 0
}

type Command struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                             // Unique command ID
	Type           CommandType            `protobuf:"varint,2,opt,name=type,proto3,enum=agent.CommandType" json:"type,omitempty"`                                                 // Type of command
	Args           []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`                                                                         // Command arguments
	Env            map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Environment variables
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                              // Max execution time (0 = no limit)
	StreamOutput   bool                   `protobuf:"varint,6,opt,name=stream_output,json=streamOutput,proto3" json:"stream_output,omitempty"`                                    // Stream stdout/stderr in real-time
	WorkingDir     string                 `protobuf:"bytes,7,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`                                           // Working directory for command
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_agent_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *Command) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Command) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *Command) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Command) GetStreamOutput() bool {
	if x != nil {
		return x.StreamOutput
	}
	return false
}

func (x *Command) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status        CommandStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=agent.CommandStatus" json:"status,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,4,opt,name=stdout,proto3" json:"stdout,omitempty"` // For streaming, partial output
	Stderr        string                 `protobuf:"bytes,5,opt,name=stderr,proto3" json:"stderr,omitempty"`
	StartedAt     int64                  `protobuf:"varint,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`       // Unix timestamp
	CompletedAt   int64                  `protobuf:"varint,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"` // Unix timestamp (0 if still running)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResponse) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_COMMAND_STATUS_UNSPECIFIED
}

func (x *CommandResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *CommandResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *CommandResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *CommandResponse) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *CommandResponse) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

type MetricsData struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	AgentId   string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	// CPU
	CpuPercent float64   `protobuf:"fixed64,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`          // Overall CPU usage %
	CpuPerCore []float64 `protobuf:"fixed64,4,rep,packed,name=cpu_per_core,json=cpuPerCore,proto3" json:"cpu_per_core,omitempty"` // Per-core usage
	// Memory
	MemoryTotal     uint64  `protobuf:"varint,5,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"` // Total RAM in bytes
	MemoryUsed      uint64  `protobuf:"varint,6,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`    // Used RAM in bytes
	MemoryAvailable uint64  `protobuf:"varint,7,opt,name=memory_available,json=memoryAvailable,proto3" json:"memory_available,omitempty"`
	MemoryPercent   float64 `protobuf:"fixed64,8,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	MemoryCached    uint64  `protobuf:"varint,16,opt,name=memory_cached,json=memoryCached,proto3" json:"memory_cached,omitempty"`
	MemoryBuffers   uint64  `protobuf:"varint,17,opt,name=memory_buffers,json=memoryBuffers,proto3" json:"memory_buffers,omitempty"`
	SwapTotal       uint64  `protobuf:"varint,18,opt,name=swap_total,json=swapTotal,proto3" json:"swap_total,omitempty"`
	SwapUsed        uint64  `protobuf:"varint,19,opt,name=swap_used,json=swapUsed,proto3" json:"swap_used,omitempty"`
	SwapFree        uint64  `protobuf:"varint,20,opt,name=swap_free,json=swapFree,proto3" json:"swap_free,omitempty"`
	SwapPercent     float64 `protobuf:"fixed64,21,opt,name=swap_percent,json=swapPercent,proto3" json:"swap_percent,omitempty"`
	// Disk
	Disks  []*DiskMetrics `protobuf:"bytes,9,rep,name=disks,proto3" json:"disks,omitempty"`
	DiskIo []*DiskIO      `protobuf:"bytes,22,rep,name=disk_io,json=diskIo,proto3" json:"disk_io,omitempty"`
	// Network
	NetworkBytesSent uint64 `protobuf:"varint,10,opt,name=network_bytes_sent,json=networkBytesSent,proto3" json:"network_bytes_sent,omitempty"`
	NetworkBytesRecv uint64 `protobuf:"varint,11,opt,name=network_bytes_recv,json=networkBytesRecv,proto3" json:"network_bytes_recv,omitempty"`
	Connections      uint64 `protobuf:"varint,23,opt,name=connections,proto3" json:"connections,omitempty"`
	// Load average (Linux)
	Load_1  float64 `protobuf:"fixed64,12,opt,name=load_1,json=load1,proto3" json:"load_1,omitempty"`
	Load_5  float64 `protobuf:"fixed64,13,opt,name=load_5,json=load5,proto3" json:"load_5,omitempty"`
	Load_15 float64 `protobuf:"fixed64,14,opt,name=load_15,json=load15,proto3" json:"load_15,omitempty"`
	// Uptime & Host
	UptimeSeconds uint64    `protobuf:"varint,15,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	HostInfo      *HostInfo `protobuf:"bytes,24,opt,name=host_info,json=hostInfo,proto3" json:"host_info,omitempty"`
	// Services & Containers
	Services   []*ServiceInfo   `protobuf:"bytes,25,rep,name=services,proto3" json:"services,omitempty"`
	Containers []*ContainerInfo `protobuf:"bytes,26,rep,name=containers,proto3" json:"containers,omitempty"`
	// Firewall
	Firewall *FirewallInfo `protobuf:"bytes,27,opt,name=firewall,proto3" json:"firewall,omitempty"`
	// Processes
	Processes []*ProcessInfo `protobuf:"bytes,28,rep,name=processes,proto3" json:"processes,omitempty"`
	// CPU extended
	CpuStealTime float64 `protobuf:"fixed64,29,opt,name=cpu_steal_time,json=cpuStealTime,proto3" json:"cpu_steal_time,omitempty"`
	CpuIowait    float64 `protobuf:"fixed64,30,opt,name=cpu_iowait,json=cpuIowait,proto3" json:"cpu_iowait,omitempty"`
	// Network extended
	NetErrin      uint64 `protobuf:"varint,31,opt,name=net_errin,json=netErrin,proto3" json:"net_errin,omitempty"`
	NetErrout     uint64 `protobuf:"varint,32,opt,name=net_errout,json=netErrout,proto3" json:"net_errout,omitempty"`
	NetDropin     uint64 `protobuf:"varint,33,opt,name=net_dropin,json=netDropin,proto3" json:"net_dropin,omitempty"`
	NetDropout    uint64 `protobuf:"varint,34,opt,name=net_dropout,json=netDropout,proto3" json:"net_dropout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsData) Reset() {
	*x = MetricsData{}
	mi := &file_proto_agent_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsData) ProtoMessage() {}

func (x *MetricsData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsData.ProtoReflect.Descriptor instead.
func (*MetricsData) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{4}
}

func (x *MetricsData) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricsData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsData) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *MetricsData) GetCpuPerCore() []float64 {
	if x != nil {
		return x.CpuPerCore
	}
	return nil
}

func (x *MetricsData) GetMemoryTotal() uint64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *MetricsData) GetMemoryUsed() uint64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *MetricsData) GetMemoryAvailable() uint64 {
	if x != nil {
		return x.MemoryAvailable
	}
	return 0
}

func (x *MetricsData) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *MetricsData) GetMemoryCached() uint64 {
	if x != nil {
		return x.MemoryCached
	}
	return 0
}

func (x *MetricsData) GetMemoryBuffers() uint64 {
	if x != nil {
		return x.MemoryBuffers
	}
	return 0
}

func (x *MetricsData) GetSwapTotal() uint64 {
	if x != nil {
		return x.SwapTotal
	}
	return 0
}

func (x *MetricsData) GetSwapUsed() uint64 {
	if x != nil {
		return x.SwapUsed
	}
	return 0
}

func (x *MetricsData) GetSwapFree() uint64 {
	if x != nil {
		return x.SwapFree
	}
	return 0
}

func (x *MetricsData) GetSwapPercent() float64 {
	if x != nil {
		return x.SwapPercent
	}
	return 0
}

func (x *MetricsData) GetDisks() []*DiskMetrics {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *MetricsData) GetDiskIo() []*DiskIO {
	if x != nil {
		return x.DiskIo
	}
	return nil
}

func (x *MetricsData) GetNetworkBytesSent() uint64 {
	if x != nil {
		return x.NetworkBytesSent
	}
	return 0
}

func (x *MetricsData) GetNetworkBytesRecv() uint64 {
	if x != nil {
		return x.NetworkBytesRecv
	}
	return 0
}

func (x *MetricsData) GetConnections() uint64 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *MetricsData) GetLoad_1() float64 {
	if x != nil {
		return x.Load_1
	}
	return 0
}

func (x *MetricsData) GetLoad_5() float64 {
	if x != nil {
		return x.Load_5
	}
	return 0
}

func (x *MetricsData) GetLoad_15() float64 {
	if x != nil {
		return x.Load_15
	}
	return 0
}

func (x *MetricsData) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *MetricsData) GetHostInfo() *HostInfo {
	if x != nil {
		return x.HostInfo
	}
	return nil
}

func (x *MetricsData) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *MetricsData) GetContainers() []*ContainerInfo {
	if x != nil {
		return x.Containers
	}
	return nil
}

func (x *MetricsData) GetFirewall() *FirewallInfo {
	if x != nil {
		return x.Firewall
	}
	return nil
}

func (x *MetricsData) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *MetricsData) GetCpuStealTime() float64 {
	if x != nil {
		return x.CpuStealTime
	}
	return 0
}

func (x *MetricsData) GetCpuIowait() float64 {
	if x != nil {
		return x.CpuIowait
	}
	return 0
}

func (x *MetricsData) GetNetErrin() uint64 {
	if x != nil {
		return x.NetErrin
	}
	return 0
}

func (x *MetricsData) GetNetErrout() uint64 {
	if x != nil {
		return x.NetErrout
	}
	return 0
}

func (x *MetricsData) GetNetDropin() uint64 {
	if x != nil {
		return x.NetDropin
	}
	return 0
}

func (x *MetricsData) GetNetDropout() uint64 {
	if x != nil {
		return x.NetDropout
	}
	return 0
}

type FirewallInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "active", "inactive"
	Rules         []*FirewallRule        `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewallInfo) Reset() {
	*x = FirewallInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallInfo) ProtoMessage() {}

func (x *FirewallInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallInfo.ProtoReflect.Descriptor instead.
func (*FirewallInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{5}
}

func (x *FirewallInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *FirewallInfo) GetRules() []*FirewallRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type FirewallRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         string                 `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	From          string                 `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	Protocol      string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirewallRule) Reset() {
	*x = FirewallRule{}
	mi := &file_proto_agent_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallRule) ProtoMessage() {}

func (x *FirewallRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallRule.ProtoReflect.Descriptor instead.
func (*FirewallRule) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{6}
}

func (x *FirewallRule) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *FirewallRule) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *FirewallRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FirewallRule) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *FirewallRule) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *FirewallRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type DiskMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MountPoint    string                 `protobuf:"bytes,1,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	Device        string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"`
	Total         uint64                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Used          uint64                 `protobuf:"varint,4,opt,name=used,proto3" json:"used,omitempty"`
	Free          uint64                 `protobuf:"varint,5,opt,name=free,proto3" json:"free,omitempty"`
	Percent       float64                `protobuf:"fixed64,6,opt,name=percent,proto3" json:"percent,omitempty"`
	Fstype        string                 `protobuf:"bytes,7,opt,name=fstype,proto3" json:"fstype,omitempty"`
	InodesTotal   uint64                 `protobuf:"varint,8,opt,name=inodes_total,json=inodesTotal,proto3" json:"inodes_total,omitempty"`
	InodesUsed    uint64                 `protobuf:"varint,9,opt,name=inodes_used,json=inodesUsed,proto3" json:"inodes_used,omitempty"`
	InodesPercent float64                `protobuf:"fixed64,10,opt,name=inodes_percent,json=inodesPercent,proto3" json:"inodes_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskMetrics) Reset() {
	*x = DiskMetrics{}
	mi := &file_proto_agent_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetrics) ProtoMessage() {}

func (x *DiskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetrics.ProtoReflect.Descriptor instead.
func (*DiskMetrics) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DiskMetrics) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *DiskMetrics) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskMetrics) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DiskMetrics) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *DiskMetrics) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *DiskMetrics) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *DiskMetrics) GetFstype() string {
	if x != nil {
		return x.Fstype
	}
	return ""
}

func (x *DiskMetrics) GetInodesTotal() uint64 {
	if x != nil {
		return x.InodesTotal
	}
	return 0
}

func (x *DiskMetrics) GetInodesUsed() uint64 {
	if x != nil {
		return x.InodesUsed
	}
	return 0
}

func (x *DiskMetrics) GetInodesPercent() float64 {
	if x != nil {
		return x.InodesPercent
	}
	return 0
}

type DiskIO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // device name
	ReadCount     uint64                 `protobuf:"varint,2,opt,name=read_count,json=readCount,proto3" json:"read_count,omitempty"`
	WriteCount    uint64                 `protobuf:"varint,3,opt,name=write_count,json=writeCount,proto3" json:"write_count,omitempty"`
	ReadBytes     uint64                 `protobuf:"varint,4,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`
	WriteBytes    uint64                 `protobuf:"varint,5,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskIO) Reset() {
	*x = DiskIO{}
	mi := &file_proto_agent_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskIO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskIO) ProtoMessage() {}

func (x *DiskIO) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskIO.ProtoReflect.Descriptor instead.
func (*DiskIO) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{8}
}

func (x *DiskIO) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiskIO) GetReadCount() uint64 {
	if x != nil {
		return x.ReadCount
	}
	return 0
}

func (x *DiskIO) GetWriteCount() uint64 {
	if x != nil {
		return x.WriteCount
	}
	return 0
}

func (x *DiskIO) GetReadBytes() uint64 {
	if x != nil {
		return x.ReadBytes
	}
	return 0
}

func (x *DiskIO) GetWriteBytes() uint64 {
	if x != nil {
		return x.WriteBytes
	}
	return 0
}

type HostInfo struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Hostname             string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os                   string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Platform             string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformFamily       string                 `protobuf:"bytes,4,opt,name=platform_family,json=platformFamily,proto3" json:"platform_family,omitempty"`
	PlatformVersion      string                 `protobuf:"bytes,5,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"`
	KernelVersion        string                 `protobuf:"bytes,6,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	KernelArch           string                 `protobuf:"bytes,7,opt,name=kernel_arch,json=kernelArch,proto3" json:"kernel_arch,omitempty"`
	BootTime             uint64                 `protobuf:"varint,8,opt,name=boot_time,json=bootTime,proto3" json:"boot_time,omitempty"`
	VirtualizationSystem string                 `protobuf:"bytes,9,opt,name=virtualization_system,json=virtualizationSystem,proto3" json:"virtualization_system,omitempty"`
	VirtualizationRole   string                 `protobuf:"bytes,10,opt,name=virtualization_role,json=virtualizationRole,proto3" json:"virtualization_role,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{9}
}

func (x *HostInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *HostInfo) GetPlatformFamily() string {
	if x != nil {
		return x.PlatformFamily
	}
	return ""
}

func (x *HostInfo) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *HostInfo) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *HostInfo) GetKernelArch() string {
	if x != nil {
		return x.KernelArch
	}
	return ""
}

func (x *HostInfo) GetBootTime() uint64 {
	if x != nil {
		return x.BootTime
	}
	return 0
}

func (x *HostInfo) GetVirtualizationSystem() string {
	if x != nil {
		return x.VirtualizationSystem
	}
	return ""
}

func (x *HostInfo) GetVirtualizationRole() string {
	if x != nil {
		return x.VirtualizationRole
	}
	return ""
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "running", "stopped", "unknown"
	Restarts      int32                  `protobuf:"varint,3,opt,name=restarts,proto3" json:"restarts,omitempty"`
	LastRestart   string                 `protobuf:"bytes,4,opt,name=last_restart,json=lastRestart,proto3" json:"last_restart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceInfo) GetRestarts() int32 {
	if x != nil {
		return x.Restarts
	}
	return 0
}

func (x *ServiceInfo) GetLastRestart() string {
	if x != nil {
		return x.LastRestart
	}
	return ""
}

type ContainerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "running", "exited", "paused"
	Health        string                 `protobuf:"bytes,5,opt,name=health,proto3" json:"health,omitempty"` // "healthy", "unhealthy", "none"
	Restarts      int32                  `protobuf:"varint,6,opt,name=restarts,proto3" json:"restarts,omitempty"`
	StartedAt     string                 `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfo.ProtoReflect.Descriptor instead.
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{11}
}

func (x *ContainerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerInfo) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *ContainerInfo) GetRestarts() int32 {
	if x != nil {
		return x.Restarts
	}
	return 0
}

func (x *ContainerInfo) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

type ProcessInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pid            int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username       string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	CpuPercent     float64                `protobuf:"fixed64,4,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent     float64                `protobuf:"fixed64,5,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	Rss            uint64                 `protobuf:"varint,6,opt,name=rss,proto3" json:"rss,omitempty"`
	CreateTime     int64                  `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	DiskReadBytes  uint64                 `protobuf:"varint,8,opt,name=disk_read_bytes,json=diskReadBytes,proto3" json:"disk_read_bytes,omitempty"`    // bytes read since last poll (delta)
	DiskWriteBytes uint64                 `protobuf:"varint,9,opt,name=disk_write_bytes,json=diskWriteBytes,proto3" json:"disk_write_bytes,omitempty"` // bytes written since last poll (delta)
	NetConnections uint32                 `protobuf:"varint,10,opt,name=net_connections,json=netConnections,proto3" json:"net_connections,omitempty"`  // active TCP/UDP connection count
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_proto_agent_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ProcessInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProcessInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *ProcessInfo) GetRss() uint64 {
	if x != nil {
		return x.Rss
	}
	return 0
}

func (x *ProcessInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ProcessInfo) GetDiskReadBytes() uint64 {
	if x != nil {
		return x.DiskReadBytes
	}
	return 0
}

func (x *ProcessInfo) GetDiskWriteBytes() uint64 {
	if x != nil {
		return x.DiskWriteBytes
	}
	return 0
}

func (x *ProcessInfo) GetNetConnections() uint32 {
	if x != nil {
		return x.NetConnections
	}
	return 0
}

type MetricsAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsAck) Reset() {
	*x = MetricsAck{}
	mi := &file_proto_agent_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsAck) ProtoMessage() {}

func (x *MetricsAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsAck.ProtoReflect.Descriptor instead.
func (*MetricsAck) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{13}
}

func (x *MetricsAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         LogLevel               `protobuf:"varint,3,opt,name=level,proto3,enum=agent.LogLevel" json:"level,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"` // "agent", "command:123", "service:nginx"
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_agent_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{14}
}

func (x *LogEntry) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type LogAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogAck) Reset() {
	*x = LogAck{}
	mi := &file_proto_agent_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogAck) ProtoMessage() {}

func (x *LogAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogAck.ProtoReflect.Descriptor instead.
func (*LogAck) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{15}
}

func (x *LogAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        AgentStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=agent.AgentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{16}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

type HeartbeatResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	ServerTime   int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// Control plane can send config updates
	ConfigUpdates map[string]string `protobuf:"bytes,3,rep,name=config_updates,json=configUpdates,proto3" json:"config_updates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{17}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *HeartbeatResponse) GetConfigUpdates() map[string]string {
	if x != nil {
		return x.ConfigUpdates
	}
	return nil
}

// SSHSyncRequest contains SSH keys to sync to authorized_keys
type SSHSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*SSHKeyEntry         `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	TargetUser    string                 `protobuf:"bytes,2,opt,name=target_user,json=targetUser,proto3" json:"target_user,omitempty"`  // Target user (e.g., "root", "ubuntu")
	ReplaceAll    bool                   `protobuf:"varint,3,opt,name=replace_all,json=replaceAll,proto3" json:"replace_all,omitempty"` // If true, replace entire file; if false, merge
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHSyncRequest) Reset() {
	*x = SSHSyncRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHSyncRequest) ProtoMessage() {}

func (x *SSHSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHSyncRequest.ProtoReflect.Descriptor instead.
func (*SSHSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{18}
}

func (x *SSHSyncRequest) GetKeys() []*SSHKeyEntry {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *SSHSyncRequest) GetTargetUser() string {
	if x != nil {
		return x.TargetUser
	}
	return ""
}

func (x *SSHSyncRequest) GetReplaceAll() bool {
	if x != nil {
		return x.ReplaceAll
	}
	return false
}

type SSHKeyEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // Key ID for tracking
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // Full public key line
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                            // Human-readable name (for comment)
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`   // Only sync active keys
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHKeyEntry) Reset() {
	*x = SSHKeyEntry{}
	mi := &file_proto_agent_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHKeyEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHKeyEntry) ProtoMessage() {}

func (x *SSHKeyEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHKeyEntry.ProtoReflect.Descriptor instead.
func (*SSHKeyEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{19}
}

func (x *SSHKeyEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SSHKeyEntry) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *SSHKeyEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SSHKeyEntry) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type SSHSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	KeysSynced    int32                  `protobuf:"varint,3,opt,name=keys_synced,json=keysSynced,proto3" json:"keys_synced,omitempty"` // Number of keys written
	BackupPath    string                 `protobuf:"bytes,4,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`  // Path to backup file if created
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHSyncResponse) Reset() {
	*x = SSHSyncResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHSyncResponse) ProtoMessage() {}

func (x *SSHSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHSyncResponse.ProtoReflect.Descriptor instead.
func (*SSHSyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{20}
}

func (x *SSHSyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SSHSyncResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SSHSyncResponse) GetKeysSynced() int32 {
	if x != nil {
		return x.KeysSynced
	}
	return 0
}

func (x *SSHSyncResponse) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

// SSHConfigRequest updates sshd_config settings
type SSHConfigRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Port            *int32                 `protobuf:"varint,1,opt,name=port,proto3,oneof" json:"port,omitempty"`                                                // SSH port (default 22)
	PermitRootLogin *bool                  `protobuf:"varint,2,opt,name=permit_root_login,json=permitRootLogin,proto3,oneof" json:"permit_root_login,omitempty"` // PermitRootLogin setting
	PasswordAuth    *bool                  `protobuf:"varint,3,opt,name=password_auth,json=passwordAuth,proto3,oneof" json:"password_auth,omitempty"`            // PasswordAuthentication setting
	PubkeyAuth      *bool                  `protobuf:"varint,4,opt,name=pubkey_auth,json=pubkeyAuth,proto3,oneof" json:"pubkey_auth,omitempty"`                  // PubkeyAuthentication setting
	RestartSshd     bool                   `protobuf:"varint,5,opt,name=restart_sshd,json=restartSshd,proto3" json:"restart_sshd,omitempty"`                     // Restart sshd after changes
	ValidateConfig  bool                   `protobuf:"varint,6,opt,name=validate_config,json=validateConfig,proto3" json:"validate_config,omitempty"`            // Run sshd -t before applying
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SSHConfigRequest) Reset() {
	*x = SSHConfigRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHConfigRequest) ProtoMessage() {}

func (x *SSHConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHConfigRequest.ProtoReflect.Descriptor instead.
func (*SSHConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{21}
}

func (x *SSHConfigRequest) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *SSHConfigRequest) GetPermitRootLogin() bool {
	if x != nil && x.PermitRootLogin != nil {
		return *x.PermitRootLogin
	}
	return false
}

func (x *SSHConfigRequest) GetPasswordAuth() bool {
	if x != nil && x.PasswordAuth != nil {
		return *x.PasswordAuth
	}
	return false
}

func (x *SSHConfigRequest) GetPubkeyAuth() bool {
	if x != nil && x.PubkeyAuth != nil {
		return *x.PubkeyAuth
	}
	return false
}

func (x *SSHConfigRequest) GetRestartSshd() bool {
	if x != nil {
		return x.RestartSshd
	}
	return false
}

func (x *SSHConfigRequest) GetValidateConfig() bool {
	if x != nil {
		return x.ValidateConfig
	}
	return false
}

type SSHConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BackupPath    string                 `protobuf:"bytes,3,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`           // Path to config backup
	SshdRestarted bool                   `protobuf:"varint,4,opt,name=sshd_restarted,json=sshdRestarted,proto3" json:"sshd_restarted,omitempty"` // Whether sshd was restarted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHConfigResponse) Reset() {
	*x = SSHConfigResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHConfigResponse) ProtoMessage() {}

func (x *SSHConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHConfigResponse.ProtoReflect.Descriptor instead.
func (*SSHConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{22}
}

func (x *SSHConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SSHConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SSHConfigResponse) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

func (x *SSHConfigResponse) GetSshdRestarted() bool {
	if x != nil {
		return x.SshdRestarted
	}
	return false
}

// SSHStatusRequest gets current SSH configuration
type SSHStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHStatusRequest) Reset() {
	*x = SSHStatusRequest{}
	mi := &file_proto_agent_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHStatusRequest) ProtoMessage() {}

func (x *SSHStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHStatusRequest.ProtoReflect.Descriptor instead.
func (*SSHStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{23}
}

type SSHStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CurrentPort         int32                  `protobuf:"varint,1,opt,name=current_port,json=currentPort,proto3" json:"current_port,omitempty"`
	PermitRootLogin     bool                   `protobuf:"varint,2,opt,name=permit_root_login,json=permitRootLogin,proto3" json:"permit_root_login,omitempty"`
	PasswordAuth        bool                   `protobuf:"varint,3,opt,name=password_auth,json=passwordAuth,proto3" json:"password_auth,omitempty"`
	PubkeyAuth          bool                   `protobuf:"varint,4,opt,name=pubkey_auth,json=pubkeyAuth,proto3" json:"pubkey_auth,omitempty"`
	SshdStatus          string                 `protobuf:"bytes,5,opt,name=sshd_status,json=sshdStatus,proto3" json:"sshd_status,omitempty"` // "running", "stopped", "unknown"
	AuthorizedKeysCount int32                  `protobuf:"varint,6,opt,name=authorized_keys_count,json=authorizedKeysCount,proto3" json:"authorized_keys_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SSHStatusResponse) Reset() {
	*x = SSHStatusResponse{}
	mi := &file_proto_agent_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHStatusResponse) ProtoMessage() {}

func (x *SSHStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHStatusResponse.ProtoReflect.Descriptor instead.
func (*SSHStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_agent_proto_rawDescGZIP(), []int{24}
}

func (x *SSHStatusResponse) GetCurrentPort() int32 {
	if x != nil {
		return x.CurrentPort
	}
	return 0
}

func (x *SSHStatusResponse) GetPermitRootLogin() bool {
	if x != nil {
		return x.PermitRootLogin
	}
	return false
}

func (x *SSHStatusResponse) GetPasswordAuth() bool {
	if x != nil {
		return x.PasswordAuth
	}
	return false
}

func (x *SSHStatusResponse) GetPubkeyAuth() bool {
	if x != nil {
		return x.PubkeyAuth
	}
	return false
}

func (x *SSHStatusResponse) GetSshdStatus() string {
	if x != nil {
		return x.SshdStatus
	}
	return ""
}

func (x *SSHStatusResponse) GetAuthorizedKeysCount() int32 {
	if x != nil {
		return x.AuthorizedKeysCount
	}
	return 0
}

var File_proto_agent_agent_proto protoreflect.FileDescriptor

const file_proto_agent_agent_proto_rawDesc = "" +
	"\n" +
	"\x17proto/agent/agent.proto\x12\x05agent\"\xc6\x02\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x1d\n" +
	"\n" +
	"os_version\x18\x05 \x01(\tR\tosVersion\x12\x12\n" +
	"\x04arch\x18\x06 \x01(\tR\x04arch\x12#\n" +
	"\ragent_version\x18\a \x01(\tR\fagentVersion\x12:\n" +
	"\x06labels\x18\b \x03(\v2\".agent.RegisterRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x96\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vassigned_id\x18\x03 \x01(\tR\n" +
	"assignedId\x12-\n" +
	"\x12heartbeat_interval\x18\x04 \x01(\x05R\x11heartbeatInterval\"\xa7\x02\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.agent.CommandTypeR\x04type\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12)\n" +
	"\x03env\x18\x04 \x03(\v2\x17.agent.Command.EnvEntryR\x03env\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12#\n" +
	"\rstream_output\x18\x06 \x01(\bR\fstreamOutput\x12\x1f\n" +
	"\vworking_dir\x18\a \x01(\tR\n" +
	"workingDir\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xed\x01\n" +
	"\x0fCommandResponse\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.agent.CommandStatusR\x06status\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x04 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x05 \x01(\tR\x06stderr\x12\x1d\n" +
	"\n" +
	"started_at\x18\x06 \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\a \x01(\x03R\vcompletedAt\"\xdd\t\n" +
	"\vMetricsData\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x01R\n" +
	"cpuPercent\x12 \n" +
	"\fcpu_per_core\x18\x04 \x03(\x01R\n" +
	"cpuPerCore\x12!\n" +
	"\fmemory_total\x18\x05 \x01(\x04R\vmemoryTotal\x12\x1f\n" +
	"\vmemory_used\x18\x06 \x01(\x04R\n" +
	"memoryUsed\x12)\n" +
	"\x10memory_available\x18\a \x01(\x04R\x0fmemoryAvailable\x12%\n" +
	"\x0ememory_percent\x18\b \x01(\x01R\rmemoryPercent\x12#\n" +
	"\rmemory_cached\x18\x10 \x01(\x04R\fmemoryCached\x12%\n" +
	"\x0ememory_buffers\x18\x11 \x01(\x04R\rmemoryBuffers\x12\x1d\n" +
	"\n" +
	"swap_total\x18\x12 \x01(\x04R\tswapTotal\x12\x1b\n" +
	"\tswap_used\x18\x13 \x01(\x04R\bswapUsed\x12\x1b\n" +
	"\tswap_free\x18\x14 \x01(\x04R\bswapFree\x12!\n" +
	"\fswap_percent\x18\x15 \x01(\x01R\vswapPercent\x12(\n" +
	"\x05disks\x18\t \x03(\v2\x12.agent.DiskMetricsR\x05disks\x12&\n" +
	"\adisk_io\x18\x16 \x03(\v2\r.agent.DiskIOR\x06diskIo\x12,\n" +
	"\x12network_bytes_sent\x18\n" +
	" \x01(\x04R\x10networkBytesSent\x12,\n" +
	"\x12network_bytes_recv\x18\v \x01(\x04R\x10networkBytesRecv\x12 \n" +
	"\vconnections\x18\x17 \x01(\x04R\vconnections\x12\x15\n" +
	"\x06load_1\x18\f \x01(\x01R\x05load1\x12\x15\n" +
	"\x06load_5\x18\r \x01(\x01R\x05load5\x12\x17\n" +
	"\aload_15\x18\x0e \x01(\x01R\x06load15\x12%\n" +
	"\x0euptime_seconds\x18\x0f \x01(\x04R\ruptimeSeconds\x12,\n" +
	"\thost_info\x18\x18 \x01(\v2\x0f.agent.HostInfoR\bhostInfo\x12.\n" +
	"\bservices\x18\x19 \x03(\v2\x12.agent.ServiceInfoR\bservices\x124\n" +
	"\n" +
	"containers\x18\x1a \x03(\v2\x14.agent.ContainerInfoR\n" +
	"containers\x12/\n" +
	"\bfirewall\x18\x1b \x01(\v2\x13.agent.FirewallInfoR\bfirewall\x120\n" +
	"\tprocesses\x18\x1c \x03(\v2\x12.agent.ProcessInfoR\tprocesses\x12$\n" +
	"\x0ecpu_steal_time\x18\x1d \x01(\x01R\fcpuStealTime\x12\x1d\n" +
	"\n" +
	"cpu_iowait\x18\x1e \x01(\x01R\tcpuIowait\x12\x1b\n" +
	"\tnet_errin\x18\x1f \x01(\x04R\bnetErrin\x12\x1d\n" +
	"\n" +
	"net_errout\x18  \x01(\x04R\tnetErrout\x12\x1d\n" +
	"\n" +
	"net_dropin\x18! \x01(\x04R\tnetDropin\x12\x1f\n" +
	"\vnet_dropout\x18\" \x01(\x04R\n" +
	"netDropout\"Q\n" +
	"\fFirewallInfo\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12)\n" +
	"\x05rules\x18\x02 \x03(\v2\x13.agent.FirewallRuleR\x05rules\"\x96\x01\n" +
	"\fFirewallRule\x12\x14\n" +
	"\x05index\x18\x01 \x01(\tR\x05index\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x12\n" +
	"\x04from\x18\x04 \x01(\tR\x04from\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\"\xa1\x02\n" +
	"\vDiskMetrics\x12\x1f\n" +
	"\vmount_point\x18\x01 \x01(\tR\n" +
	"mountPoint\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x04 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x05 \x01(\x04R\x04free\x12\x18\n" +
	"\apercent\x18\x06 \x01(\x01R\apercent\x12\x16\n" +
	"\x06fstype\x18\a \x01(\tR\x06fstype\x12!\n" +
	"\finodes_total\x18\b \x01(\x04R\vinodesTotal\x12\x1f\n" +
	"\vinodes_used\x18\t \x01(\x04R\n" +
	"inodesUsed\x12%\n" +
	"\x0einodes_percent\x18\n" +
	" \x01(\x01R\rinodesPercent\"\x9c\x01\n" +
	"\x06DiskIO\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"read_count\x18\x02 \x01(\x04R\treadCount\x12\x1f\n" +
	"\vwrite_count\x18\x03 \x01(\x04R\n" +
	"writeCount\x12\x1d\n" +
	"\n" +
	"read_bytes\x18\x04 \x01(\x04R\treadBytes\x12\x1f\n" +
	"\vwrite_bytes\x18\x05 \x01(\x04R\n" +
	"writeBytes\"\xf1\x02\n" +
	"\bHostInfo\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12'\n" +
	"\x0fplatform_family\x18\x04 \x01(\tR\x0eplatformFamily\x12)\n" +
	"\x10platform_version\x18\x05 \x01(\tR\x0fplatformVersion\x12%\n" +
	"\x0ekernel_version\x18\x06 \x01(\tR\rkernelVersion\x12\x1f\n" +
	"\vkernel_arch\x18\a \x01(\tR\n" +
	"kernelArch\x12\x1b\n" +
	"\tboot_time\x18\b \x01(\x04R\bbootTime\x123\n" +
	"\x15virtualization_system\x18\t \x01(\tR\x14virtualizationSystem\x12/\n" +
	"\x13virtualization_role\x18\n" +
	" \x01(\tR\x12virtualizationRole\"x\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\brestarts\x18\x03 \x01(\x05R\brestarts\x12!\n" +
	"\flast_restart\x18\x04 \x01(\tR\vlastRestart\"\xb4\x01\n" +
	"\rContainerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06health\x18\x05 \x01(\tR\x06health\x12\x1a\n" +
	"\brestarts\x18\x06 \x01(\x05R\brestarts\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\tR\tstartedAt\"\xbf\x02\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1f\n" +
	"\vcpu_percent\x18\x04 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x05 \x01(\x01R\n" +
	"memPercent\x12\x10\n" +
	"\x03rss\x18\x06 \x01(\x04R\x03rss\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\x03R\n" +
	"createTime\x12&\n" +
	"\x0fdisk_read_bytes\x18\b \x01(\x04R\rdiskReadBytes\x12(\n" +
	"\x10disk_write_bytes\x18\t \x01(\x04R\x0ediskWriteBytes\x12'\n" +
	"\x0fnet_connections\x18\n" +
	" \x01(\rR\x0enetConnections\"(\n" +
	"\n" +
	"MetricsAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\"\x94\x02\n" +
	"\bLogEntry\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12%\n" +
	"\x05level\x18\x03 \x01(\x0e2\x0f.agent.LogLevelR\x05level\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x129\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1d.agent.LogEntry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\x06LogAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\"w\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.agent.AgentStatusR\x06status\"\xee\x01\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\x12R\n" +
	"\x0econfig_updates\x18\x03 \x03(\v2+.agent.HeartbeatResponse.ConfigUpdatesEntryR\rconfigUpdates\x1a@\n" +
	"\x12ConfigUpdatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\x0eSSHSyncRequest\x12&\n" +
	"\x04keys\x18\x01 \x03(\v2\x12.agent.SSHKeyEntryR\x04keys\x12\x1f\n" +
	"\vtarget_user\x18\x02 \x01(\tR\n" +
	"targetUser\x12\x1f\n" +
	"\vreplace_all\x18\x03 \x01(\bR\n" +
	"replaceAll\"m\n" +
	"\vSSHKeyEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\"\x87\x01\n" +
	"\x0fSSHSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vkeys_synced\x18\x03 \x01(\x05R\n" +
	"keysSynced\x12\x1f\n" +
	"\vbackup_path\x18\x04 \x01(\tR\n" +
	"backupPath\"\xb9\x02\n" +
	"\x10SSHConfigRequest\x12\x17\n" +
	"\x04port\x18\x01 \x01(\x05H\x00R\x04port\x88\x01\x01\x12/\n" +
	"\x11permit_root_login\x18\x02 \x01(\bH\x01R\x0fpermitRootLogin\x88\x01\x01\x12(\n" +
	"\rpassword_auth\x18\x03 \x01(\bH\x02R\fpasswordAuth\x88\x01\x01\x12$\n" +
	"\vpubkey_auth\x18\x04 \x01(\bH\x03R\n" +
	"pubkeyAuth\x88\x01\x01\x12!\n" +
	"\frestart_sshd\x18\x05 \x01(\bR\vrestartSshd\x12'\n" +
	"\x0fvalidate_config\x18\x06 \x01(\bR\x0evalidateConfigB\a\n" +
	"\x05_portB\x14\n" +
	"\x12_permit_root_loginB\x10\n" +
	"\x0e_password_authB\x0e\n" +
	"\f_pubkey_auth\"\x8f\x01\n" +
	"\x11SSHConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vbackup_path\x18\x03 \x01(\tR\n" +
	"backupPath\x12%\n" +
	"\x0esshd_restarted\x18\x04 \x01(\bR\rsshdRestarted\"\x12\n" +
	"\x10SSHStatusRequest\"\xfd\x01\n" +
	"\x11SSHStatusResponse\x12!\n" +
	"\fcurrent_port\x18\x01 \x01(\x05R\vcurrentPort\x12*\n" +
	"\x11permit_root_login\x18\x02 \x01(\bR\x0fpermitRootLogin\x12#\n" +
	"\rpassword_auth\x18\x03 \x01(\bR\fpasswordAuth\x12\x1f\n" +
	"\vpubkey_auth\x18\x04 \x01(\bR\n" +
	"pubkeyAuth\x12\x1f\n" +
	"\vsshd_status\x18\x05 \x01(\tR\n" +
	"sshdStatus\x122\n" +
	"\x15authorized_keys_count\x18\x06 \x01(\x05R\x13authorizedKeysCount*\xf4\x01\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11COMMAND_TYPE_EXEC\x10\x01\x12\x18\n" +
	"\x14COMMAND_TYPE_INSTALL\x10\x02\x12\x18\n" +
	"\x14COMMAND_TYPE_SERVICE\x10\x03\x12\x17\n" +
	"\x13COMMAND_TYPE_DOCKER\x10\x04\x12\x15\n" +
	"\x11COMMAND_TYPE_FILE\x10\x05\x12\x17\n" +
	"\x13COMMAND_TYPE_SCRIPT\x10\x06\x12\x14\n" +
	"\x10COMMAND_TYPE_SSH\x10\a\x12\x1d\n" +
	"\x19COMMAND_TYPE_CHECK_MODULE\x10\b*\xda\x01\n" +
	"\rCommandStatus\x12\x1e\n" +
	"\x1aCOMMAND_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16COMMAND_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16COMMAND_STATUS_RUNNING\x10\x02\x12\x1c\n" +
	"\x18COMMAND_STATUS_COMPLETED\x10\x03\x12\x19\n" +
	"\x15COMMAND_STATUS_FAILED\x10\x04\x12\x1a\n" +
	"\x16COMMAND_STATUS_TIMEOUT\x10\x05\x12\x1c\n" +
	"\x18COMMAND_STATUS_CANCELLED\x10\x06*w\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOG_LEVEL_DEBUG\x10\x01\x12\x12\n" +
	"\x0eLOG_LEVEL_INFO\x10\x02\x12\x12\n" +
	"\x0eLOG_LEVEL_WARN\x10\x03\x12\x13\n" +
	"\x0fLOG_LEVEL_ERROR\x10\x04*q\n" +
	"\vAgentStatus\x12\x1c\n" +
	"\x18AGENT_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11AGENT_STATUS_IDLE\x10\x01\x12\x15\n" +
	"\x11AGENT_STATUS_BUSY\x10\x02\x12\x16\n" +
	"\x12AGENT_STATUS_ERROR\x10\x032\xb6\x02\n" +
	"\fAgentService\x12;\n" +
	"\bRegister\x12\x16.agent.RegisterRequest\x1a\x17.agent.RegisterResponse\x12;\n" +
	"\rCommandStream\x12\x16.agent.CommandResponse\x1a\x0e.agent.Command(\x010\x01\x12:\n" +
	"\rStreamMetrics\x12\x12.agent.MetricsData\x1a\x11.agent.MetricsAck(\x010\x01\x120\n" +
	"\n" +
	"StreamLogs\x12\x0f.agent.LogEntry\x1a\r.agent.LogAck(\x010\x01\x12>\n" +
	"\tHeartbeat\x12\x17.agent.HeartbeatRequest\x1a\x18.agent.HeartbeatResponseB0Z.github.com/cloudnan-tech/cloudnan-agent/proto/agentb\x06proto3"

var (
	file_proto_agent_agent_proto_rawDescOnce sync.Once
	file_proto_agent_agent_proto_rawDescData []byte
)

func file_proto_agent_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_agent_proto_rawDesc), len(file_proto_agent_agent_proto_rawDesc)))
	})
	return file_proto_agent_agent_proto_rawDescData
}

var file_proto_agent_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_agent_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_agent_agent_proto_goTypes = []any{
	(CommandType)(0),          // 0: agent.CommandType
	(CommandStatus)(0),        // 1: agent.CommandStatus
	(LogLevel)(0),             // 2: agent.LogLevel
	(AgentStatus)(0),          // 3: agent.AgentStatus
	(*RegisterRequest)(nil),   // 4: agent.RegisterRequest
	(*RegisterResponse)(nil),  // 5: agent.RegisterResponse
	(*Command)(nil),           // 6: agent.Command
	(*CommandResponse)(nil),   // 7: agent.CommandResponse
	(*MetricsData)(nil),       // 8: agent.MetricsData
	(*FirewallInfo)(nil),      // 9: agent.FirewallInfo
	(*FirewallRule)(nil),      // 10: agent.FirewallRule
	(*DiskMetrics)(nil),       // 11: agent.DiskMetrics
	(*DiskIO)(nil),            // 12: agent.DiskIO
	(*HostInfo)(nil),          // 13: agent.HostInfo
	(*ServiceInfo)(nil),       // 14: agent.ServiceInfo
	(*ContainerInfo)(nil),     // 15: agent.ContainerInfo
	(*ProcessInfo)(nil),       // 16: agent.ProcessInfo
	(*MetricsAck)(nil),        // 17: agent.MetricsAck
	(*LogEntry)(nil),          // 18: agent.LogEntry
	(*LogAck)(nil),            // 19: agent.LogAck
	(*HeartbeatRequest)(nil),  // 20: agent.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 21: agent.HeartbeatResponse
	(*SSHSyncRequest)(nil),    // 22: agent.SSHSyncRequest
	(*SSHKeyEntry)(nil),       // 23: agent.SSHKeyEntry
	(*SSHSyncResponse)(nil),   // 24: agent.SSHSyncResponse
	(*SSHConfigRequest)(nil),  // 25: agent.SSHConfigRequest
	(*SSHConfigResponse)(nil), // 26: agent.SSHConfigResponse
	(*SSHStatusRequest)(nil),  // 27: agent.SSHStatusRequest
	(*SSHStatusResponse)(nil), // 28: agent.SSHStatusResponse
	nil,                       // 29: agent.RegisterRequest.LabelsEntry
	nil,                       // 30: agent.Command.EnvEntry
	nil,                       // 31: agent.LogEntry.MetadataEntry
	nil,                       // 32: agent.HeartbeatResponse.ConfigUpdatesEntry
}
var file_proto_agent_agent_proto_depIdxs = []int32{
	29, // 0: agent.RegisterRequest.labels:type_name -> agent.RegisterRequest.LabelsEntry
	0,  // 1: agent.Command.type:type_name -> agent.CommandType
	30, // 2: agent.Command.env:type_name -> agent.Command.EnvEntry
	1,  // 3: agent.CommandResponse.status:type_name -> agent.CommandStatus
	11, // 4: agent.MetricsData.disks:type_name -> agent.DiskMetrics
	12, // 5: agent.MetricsData.disk_io:type_name -> agent.DiskIO
	13, // 6: agent.MetricsData.host_info:type_name -> agent.HostInfo
	14, // 7: agent.MetricsData.services:type_name -> agent.ServiceInfo
	15, // 8: agent.MetricsData.containers:type_name -> agent.ContainerInfo
	9,  // 9: agent.MetricsData.firewall:type_name -> agent.FirewallInfo
	16, // 10: agent.MetricsData.processes:type_name -> agent.ProcessInfo
	10, // 11: agent.FirewallInfo.rules:type_name -> agent.FirewallRule
	2,  // 12: agent.LogEntry.level:type_name -> agent.LogLevel
	31, // 13: agent.LogEntry.metadata:type_name -> agent.LogEntry.MetadataEntry
	3,  // 14: agent.HeartbeatRequest.status:type_name -> agent.AgentStatus
	32, // 15: agent.HeartbeatResponse.config_updates:type_name -> agent.HeartbeatResponse.ConfigUpdatesEntry
	23, // 16: agent.SSHSyncRequest.keys:type_name -> agent.SSHKeyEntry
	4,  // 17: agent.AgentService.Register:input_type -> agent.RegisterRequest
	7,  // 18: agent.AgentService.CommandStream:input_type -> agent.CommandResponse
	8,  // 19: agent.AgentService.StreamMetrics:input_type -> agent.MetricsData
	18, // 20: agent.AgentService.StreamLogs:input_type -> agent.LogEntry
	20, // 21: agent.AgentService.Heartbeat:input_type -> agent.HeartbeatRequest
	5,  // 22: agent.AgentService.Register:output_type -> agent.RegisterResponse
	6,  // 23: agent.AgentService.CommandStream:output_type -> agent.Command
	17, // 24: agent.AgentService.StreamMetrics:output_type -> agent.MetricsAck
	19, // 25: agent.AgentService.StreamLogs:output_type -> agent.LogAck
	21, // 26: agent.AgentService.Heartbeat:output_type -> agent.HeartbeatResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_agent_agent_proto_init() }
func file_proto_agent_agent_proto_init() {
	if File_proto_agent_agent_proto != nil {
		return
	}
	file_proto_agent_agent_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_agent_proto_rawDesc), len(file_proto_agent_agent_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_agent_proto = out.File
	file_proto_agent_agent_proto_goTypes = nil
	file_proto_agent_agent_proto_depIdxs = nil
}
